// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEUkxEgyN2vFpldpww7cuu5rLJ5-qMANw',
    appId: '1:918818993:web:b10b20b67b981051509290',
    messagingSenderId: '918818993',
    projectId: 'lastproject-94715',
    authDomain: 'lastproject-94715.firebaseapp.com',
    storageBucket: 'lastproject-94715.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD44Wdx6KnhGwcZi4lpH4rEFAjhZLhKuHc',
    appId: '1:918818993:android:f2938d89e7227d74509290',
    messagingSenderId: '918818993',
    projectId: 'lastproject-94715',
    storageBucket: 'lastproject-94715.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBYBQ5Kqz1oIX5H4_-3OpCgJpYh_vFivA',
    appId: '1:918818993:ios:2d64a8f9366bb1b0509290',
    messagingSenderId: '918818993',
    projectId: 'lastproject-94715',
    storageBucket: 'lastproject-94715.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBYBQ5Kqz1oIX5H4_-3OpCgJpYh_vFivA',
    appId: '1:918818993:ios:7622aa87b5307f34509290',
    messagingSenderId: '918818993',
    projectId: 'lastproject-94715',
    storageBucket: 'lastproject-94715.appspot.com',
    iosBundleId: 'com.example.finalProject.RunnerTests',
  );
}
